//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `BatteryStatus.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <BatteryStatus.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::RoboCompBatteryStatus::HardwareFailedException> iceC_RoboCompBatteryStatus_HardwareFailedException_init("::RoboCompBatteryStatus::HardwareFailedException");

const ::std::string iceC_RoboCompBatteryStatus_BatteryStatus_ids[2] =
{
    "::Ice::Object",
    "::RoboCompBatteryStatus::BatteryStatus"
};
const ::std::string iceC_RoboCompBatteryStatus_BatteryStatus_ops[] =
{
    "getBatteryState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name = "getBatteryState";

}

RoboCompBatteryStatus::HardwareFailedException::~HardwareFailedException()
{
}

const ::std::string&
RoboCompBatteryStatus::HardwareFailedException::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompBatteryStatus::HardwareFailedException";
    return typeId;
}

bool
RoboCompBatteryStatus::BatteryStatus::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompBatteryStatus_BatteryStatus_ids, iceC_RoboCompBatteryStatus_BatteryStatus_ids + 2, s);
}

::std::vector<::std::string>
RoboCompBatteryStatus::BatteryStatus::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompBatteryStatus_BatteryStatus_ids[0], &iceC_RoboCompBatteryStatus_BatteryStatus_ids[2]);
}

::std::string
RoboCompBatteryStatus::BatteryStatus::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompBatteryStatus::BatteryStatus::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompBatteryStatus::BatteryStatus";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompBatteryStatus::BatteryStatus::_iceD_getBatteryState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    TBattery ret = this->getBatteryState(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompBatteryStatus::BatteryStatus::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompBatteryStatus_BatteryStatus_ops, iceC_RoboCompBatteryStatus_BatteryStatus_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompBatteryStatus_BatteryStatus_ops)
    {
        case 0:
        {
            return _iceD_getBatteryState(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompBatteryStatus::BatteryStatusPrx::_iceI_getBatteryState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompBatteryStatus::TBattery>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name);
    outAsync->invoke(iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompBatteryStatus::BatteryStatusPrx::_newInstance() const
{
    return ::IceInternal::createProxy<BatteryStatusPrx>();
}
/// \endcond

const ::std::string&
RoboCompBatteryStatus::BatteryStatusPrx::ice_staticId()
{
    return BatteryStatus::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name = "getBatteryState";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompBatteryStatus::HardwareFailedException> iceC_RoboCompBatteryStatus_HardwareFailedException_init("::RoboCompBatteryStatus::HardwareFailedException");

}

RoboCompBatteryStatus::HardwareFailedException::HardwareFailedException(const ::std::string& what) :
    ::Ice::UserException(),
    what(what)
{
}

#ifdef ICE_CPP11_COMPILER
RoboCompBatteryStatus::HardwareFailedException::~HardwareFailedException()
{
}
#else
RoboCompBatteryStatus::HardwareFailedException::~HardwareFailedException() throw()
{
}
#endif

::std::string
RoboCompBatteryStatus::HardwareFailedException::ice_id() const
{
    return "::RoboCompBatteryStatus::HardwareFailedException";
}

RoboCompBatteryStatus::HardwareFailedException*
RoboCompBatteryStatus::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompBatteryStatus::HardwareFailedException::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
RoboCompBatteryStatus::HardwareFailedException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::RoboCompBatteryStatus::HardwareFailedException", -1, true);
    ::Ice::StreamWriter< HardwareFailedException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompBatteryStatus::HardwareFailedException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HardwareFailedException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompBatteryStatus::upCast(BatteryStatus* p) { return p; }

void
::IceProxy::RoboCompBatteryStatus::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< BatteryStatus>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new BatteryStatus;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompBatteryStatus::BatteryStatus::_iceI_begin_getBatteryState(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompBatteryStatus::TBattery
IceProxy::RoboCompBatteryStatus::BatteryStatus::end_getBatteryState(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompBatteryStatus_BatteryStatus_getBatteryState_name);
    ::RoboCompBatteryStatus::TBattery ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompBatteryStatus::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompBatteryStatus::BatteryStatus::_newInstance() const
{
    return new BatteryStatus;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompBatteryStatus::BatteryStatus::ice_staticId()
{
    return ::RoboCompBatteryStatus::BatteryStatus::ice_staticId();
}

RoboCompBatteryStatus::BatteryStatus::~BatteryStatus()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompBatteryStatus::upCast(BatteryStatus* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompBatteryStatus_BatteryStatus_ids[2] =
{
    "::Ice::Object",
    "::RoboCompBatteryStatus::BatteryStatus"
};

}

bool
RoboCompBatteryStatus::BatteryStatus::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompBatteryStatus_BatteryStatus_ids, iceC_RoboCompBatteryStatus_BatteryStatus_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompBatteryStatus::BatteryStatus::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompBatteryStatus_BatteryStatus_ids[0], &iceC_RoboCompBatteryStatus_BatteryStatus_ids[2]);
}

const ::std::string&
RoboCompBatteryStatus::BatteryStatus::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompBatteryStatus::BatteryStatus::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompBatteryStatus::BatteryStatus";
    return typeId;
#else
    return iceC_RoboCompBatteryStatus_BatteryStatus_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompBatteryStatus::BatteryStatus::_iceD_getBatteryState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    TBattery ret = this->getBatteryState(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompBatteryStatus_BatteryStatus_all[] =
{
    "getBatteryState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompBatteryStatus::BatteryStatus::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompBatteryStatus_BatteryStatus_all, iceC_RoboCompBatteryStatus_BatteryStatus_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompBatteryStatus_BatteryStatus_all)
    {
        case 0:
        {
            return _iceD_getBatteryState(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompBatteryStatus::BatteryStatus::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< BatteryStatus, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompBatteryStatus::BatteryStatus::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< BatteryStatus, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompBatteryStatus::_icePatchObjectPtr(BatteryStatusPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = BatteryStatusPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(BatteryStatus::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
