//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `EmergencyStop.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <EmergencyStop.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompEmergencyStop_EmergencyStop_ids[2] =
{
    "::Ice::Object",
    "::RoboCompEmergencyStop::EmergencyStop"
};
const ::std::string iceC_RoboCompEmergencyStop_EmergencyStop_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "isEmergency"
};
const ::std::string iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name = "isEmergency";

}

bool
RoboCompEmergencyStop::EmergencyStop::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompEmergencyStop_EmergencyStop_ids, iceC_RoboCompEmergencyStop_EmergencyStop_ids + 2, s);
}

::std::vector<::std::string>
RoboCompEmergencyStop::EmergencyStop::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompEmergencyStop_EmergencyStop_ids[0], &iceC_RoboCompEmergencyStop_EmergencyStop_ids[2]);
}

::std::string
RoboCompEmergencyStop::EmergencyStop::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompEmergencyStop::EmergencyStop::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompEmergencyStop::EmergencyStop";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompEmergencyStop::EmergencyStop::_iceD_isEmergency(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->isEmergency(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmergencyStop::EmergencyStop::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompEmergencyStop_EmergencyStop_ops, iceC_RoboCompEmergencyStop_EmergencyStop_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompEmergencyStop_EmergencyStop_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_isEmergency(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmergencyStop::EmergencyStopPrx::_iceI_isEmergency(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name);
    outAsync->invoke(iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompEmergencyStop::EmergencyStopPrx::_newInstance() const
{
    return ::IceInternal::createProxy<EmergencyStopPrx>();
}
/// \endcond

const ::std::string&
RoboCompEmergencyStop::EmergencyStopPrx::ice_staticId()
{
    return EmergencyStop::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name = "isEmergency";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompEmergencyStop::upCast(EmergencyStop* p) { return p; }

void
::IceProxy::RoboCompEmergencyStop::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< EmergencyStop>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new EmergencyStop;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompEmergencyStop::EmergencyStop::_iceI_begin_isEmergency(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::RoboCompEmergencyStop::EmergencyStop::end_isEmergency(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompEmergencyStop_EmergencyStop_isEmergency_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompEmergencyStop::EmergencyStop::_newInstance() const
{
    return new EmergencyStop;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompEmergencyStop::EmergencyStop::ice_staticId()
{
    return ::RoboCompEmergencyStop::EmergencyStop::ice_staticId();
}

RoboCompEmergencyStop::EmergencyStop::~EmergencyStop()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompEmergencyStop::upCast(EmergencyStop* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompEmergencyStop_EmergencyStop_ids[2] =
{
    "::Ice::Object",
    "::RoboCompEmergencyStop::EmergencyStop"
};

}

bool
RoboCompEmergencyStop::EmergencyStop::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompEmergencyStop_EmergencyStop_ids, iceC_RoboCompEmergencyStop_EmergencyStop_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompEmergencyStop::EmergencyStop::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompEmergencyStop_EmergencyStop_ids[0], &iceC_RoboCompEmergencyStop_EmergencyStop_ids[2]);
}

const ::std::string&
RoboCompEmergencyStop::EmergencyStop::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompEmergencyStop::EmergencyStop::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompEmergencyStop::EmergencyStop";
    return typeId;
#else
    return iceC_RoboCompEmergencyStop_EmergencyStop_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompEmergencyStop::EmergencyStop::_iceD_isEmergency(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->isEmergency(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompEmergencyStop_EmergencyStop_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "isEmergency"
};

}

/// \cond INTERNAL
bool
RoboCompEmergencyStop::EmergencyStop::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompEmergencyStop_EmergencyStop_all, iceC_RoboCompEmergencyStop_EmergencyStop_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompEmergencyStop_EmergencyStop_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_isEmergency(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompEmergencyStop::EmergencyStop::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< EmergencyStop, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompEmergencyStop::EmergencyStop::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< EmergencyStop, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmergencyStop::_icePatchObjectPtr(EmergencyStopPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = EmergencyStopPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(EmergencyStop::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
