//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `EmotionalMotor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <EmotionalMotor.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_ids[2] =
{
    "::Ice::Object",
    "::RoboCompEmotionalMotor::EmotionalMotor"
};
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_ops[] =
{
    "expressAnger",
    "expressDisgust",
    "expressFear",
    "expressJoy",
    "expressSadness",
    "expressSurprise",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "isanybodythere",
    "listening",
    "pupposition",
    "talking"
};
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressAnger_name = "expressAnger";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressDisgust_name = "expressDisgust";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressFear_name = "expressFear";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressJoy_name = "expressJoy";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSadness_name = "expressSadness";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSurprise_name = "expressSurprise";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_isanybodythere_name = "isanybodythere";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_listening_name = "listening";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_pupposition_name = "pupposition";
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_talking_name = "talking";

}

bool
RoboCompEmotionalMotor::EmotionalMotor::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompEmotionalMotor_EmotionalMotor_ids, iceC_RoboCompEmotionalMotor_EmotionalMotor_ids + 2, s);
}

::std::vector<::std::string>
RoboCompEmotionalMotor::EmotionalMotor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompEmotionalMotor_EmotionalMotor_ids[0], &iceC_RoboCompEmotionalMotor_EmotionalMotor_ids[2]);
}

::std::string
RoboCompEmotionalMotor::EmotionalMotor::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompEmotionalMotor::EmotionalMotor::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompEmotionalMotor::EmotionalMotor";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressAnger(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->expressAnger(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressDisgust(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->expressDisgust(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressFear(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->expressFear(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressJoy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->expressJoy(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressSadness(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->expressSadness(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressSurprise(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->expressSurprise(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_isanybodythere(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    bool iceP_isAny;
    istr->readAll(iceP_isAny);
    inS.endReadParams();
    this->isanybodythere(iceP_isAny, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_listening(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    bool iceP_setListening;
    istr->readAll(iceP_setListening);
    inS.endReadParams();
    this->listening(iceP_setListening, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_pupposition(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    float iceP_x;
    float iceP_y;
    istr->readAll(iceP_x, iceP_y);
    inS.endReadParams();
    this->pupposition(iceP_x, iceP_y, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_talking(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    bool iceP_setTalk;
    istr->readAll(iceP_setTalk);
    inS.endReadParams();
    this->talking(iceP_setTalk, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompEmotionalMotor_EmotionalMotor_ops, iceC_RoboCompEmotionalMotor_EmotionalMotor_ops + 14, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompEmotionalMotor_EmotionalMotor_ops)
    {
        case 0:
        {
            return _iceD_expressAnger(in, current);
        }
        case 1:
        {
            return _iceD_expressDisgust(in, current);
        }
        case 2:
        {
            return _iceD_expressFear(in, current);
        }
        case 3:
        {
            return _iceD_expressJoy(in, current);
        }
        case 4:
        {
            return _iceD_expressSadness(in, current);
        }
        case 5:
        {
            return _iceD_expressSurprise(in, current);
        }
        case 6:
        {
            return _iceD_ice_id(in, current);
        }
        case 7:
        {
            return _iceD_ice_ids(in, current);
        }
        case 8:
        {
            return _iceD_ice_isA(in, current);
        }
        case 9:
        {
            return _iceD_ice_ping(in, current);
        }
        case 10:
        {
            return _iceD_isanybodythere(in, current);
        }
        case 11:
        {
            return _iceD_listening(in, current);
        }
        case 12:
        {
            return _iceD_pupposition(in, current);
        }
        case 13:
        {
            return _iceD_talking(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_expressAnger(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressAnger_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_expressDisgust(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressDisgust_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_expressFear(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressFear_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_expressJoy(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressJoy_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_expressSadness(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSadness_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_expressSurprise(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSurprise_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_isanybodythere(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, bool iceP_isAny, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_isanybodythere_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_isAny);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_listening(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, bool iceP_setListening, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_listening_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_setListening);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_pupposition(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, float iceP_x, float iceP_y, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_pupposition_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_x, iceP_y);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::EmotionalMotorPrx::_iceI_talking(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, bool iceP_setTalk, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_talking_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_setTalk);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompEmotionalMotor::EmotionalMotorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<EmotionalMotorPrx>();
}
/// \endcond

const ::std::string&
RoboCompEmotionalMotor::EmotionalMotorPrx::ice_staticId()
{
    return EmotionalMotor::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressAnger_name = "expressAnger";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressDisgust_name = "expressDisgust";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressFear_name = "expressFear";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressJoy_name = "expressJoy";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSadness_name = "expressSadness";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSurprise_name = "expressSurprise";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_isanybodythere_name = "isanybodythere";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_listening_name = "listening";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_pupposition_name = "pupposition";

const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_talking_name = "talking";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompEmotionalMotor::upCast(EmotionalMotor* p) { return p; }

void
::IceProxy::RoboCompEmotionalMotor::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< EmotionalMotor>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new EmotionalMotor;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_expressAnger(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressAnger_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressAnger_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressAnger_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_expressAnger(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressAnger_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_expressDisgust(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressDisgust_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressDisgust_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressDisgust_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_expressDisgust(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressDisgust_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_expressFear(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressFear_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressFear_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressFear_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_expressFear(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressFear_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_expressJoy(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressJoy_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressJoy_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressJoy_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_expressJoy(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressJoy_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_expressSadness(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSadness_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSadness_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSadness_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_expressSadness(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSadness_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_expressSurprise(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSurprise_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSurprise_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSurprise_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_expressSurprise(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_expressSurprise_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_isanybodythere(bool iceP_isAny, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_isanybodythere_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_isanybodythere_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_isAny);
        result->endWriteParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_isanybodythere_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_isanybodythere(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_isanybodythere_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_listening(bool iceP_setListening, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_listening_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_listening_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_setListening);
        result->endWriteParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_listening_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_listening(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_listening_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_pupposition(::Ice::Float iceP_x, ::Ice::Float iceP_y, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_pupposition_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_pupposition_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_x);
        ostr->write(iceP_y);
        result->endWriteParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_pupposition_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_pupposition(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_pupposition_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_iceI_begin_talking(bool iceP_setTalk, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompEmotionalMotor_EmotionalMotor_talking_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompEmotionalMotor_EmotionalMotor_talking_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_setTalk);
        result->endWriteParams();
        result->invoke(iceC_RoboCompEmotionalMotor_EmotionalMotor_talking_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::end_talking(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompEmotionalMotor_EmotionalMotor_talking_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::_newInstance() const
{
    return new EmotionalMotor;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompEmotionalMotor::EmotionalMotor::ice_staticId()
{
    return ::RoboCompEmotionalMotor::EmotionalMotor::ice_staticId();
}

RoboCompEmotionalMotor::EmotionalMotor::~EmotionalMotor()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompEmotionalMotor::upCast(EmotionalMotor* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_ids[2] =
{
    "::Ice::Object",
    "::RoboCompEmotionalMotor::EmotionalMotor"
};

}

bool
RoboCompEmotionalMotor::EmotionalMotor::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompEmotionalMotor_EmotionalMotor_ids, iceC_RoboCompEmotionalMotor_EmotionalMotor_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompEmotionalMotor::EmotionalMotor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompEmotionalMotor_EmotionalMotor_ids[0], &iceC_RoboCompEmotionalMotor_EmotionalMotor_ids[2]);
}

const ::std::string&
RoboCompEmotionalMotor::EmotionalMotor::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompEmotionalMotor::EmotionalMotor::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompEmotionalMotor::EmotionalMotor";
    return typeId;
#else
    return iceC_RoboCompEmotionalMotor_EmotionalMotor_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressAnger(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->expressAnger(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressDisgust(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->expressDisgust(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressFear(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->expressFear(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressJoy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->expressJoy(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressSadness(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->expressSadness(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_expressSurprise(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->expressSurprise(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_isanybodythere(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    bool iceP_isAny;
    istr->read(iceP_isAny);
    inS.endReadParams();
    this->isanybodythere(iceP_isAny, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_listening(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    bool iceP_setListening;
    istr->read(iceP_setListening);
    inS.endReadParams();
    this->listening(iceP_setListening, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_pupposition(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Float iceP_x;
    ::Ice::Float iceP_y;
    istr->read(iceP_x);
    istr->read(iceP_y);
    inS.endReadParams();
    this->pupposition(iceP_x, iceP_y, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceD_talking(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    bool iceP_setTalk;
    istr->read(iceP_setTalk);
    inS.endReadParams();
    this->talking(iceP_setTalk, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompEmotionalMotor_EmotionalMotor_all[] =
{
    "expressAnger",
    "expressDisgust",
    "expressFear",
    "expressJoy",
    "expressSadness",
    "expressSurprise",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "isanybodythere",
    "listening",
    "pupposition",
    "talking"
};

}

/// \cond INTERNAL
bool
RoboCompEmotionalMotor::EmotionalMotor::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompEmotionalMotor_EmotionalMotor_all, iceC_RoboCompEmotionalMotor_EmotionalMotor_all + 14, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompEmotionalMotor_EmotionalMotor_all)
    {
        case 0:
        {
            return _iceD_expressAnger(in, current);
        }
        case 1:
        {
            return _iceD_expressDisgust(in, current);
        }
        case 2:
        {
            return _iceD_expressFear(in, current);
        }
        case 3:
        {
            return _iceD_expressJoy(in, current);
        }
        case 4:
        {
            return _iceD_expressSadness(in, current);
        }
        case 5:
        {
            return _iceD_expressSurprise(in, current);
        }
        case 6:
        {
            return _iceD_ice_id(in, current);
        }
        case 7:
        {
            return _iceD_ice_ids(in, current);
        }
        case 8:
        {
            return _iceD_ice_isA(in, current);
        }
        case 9:
        {
            return _iceD_ice_ping(in, current);
        }
        case 10:
        {
            return _iceD_isanybodythere(in, current);
        }
        case 11:
        {
            return _iceD_listening(in, current);
        }
        case 12:
        {
            return _iceD_pupposition(in, current);
        }
        case 13:
        {
            return _iceD_talking(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompEmotionalMotor::EmotionalMotor::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< EmotionalMotor, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompEmotionalMotor::EmotionalMotor::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< EmotionalMotor, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompEmotionalMotor::_icePatchObjectPtr(EmotionalMotorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = EmotionalMotorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(EmotionalMotor::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
